### ISSUE TITLE
Crumbs should be enabled by default

### ISSUE THREAD

**Issue by Daniel15** [jenkins-khan/jenkins-php-api#49]
All modern Jenkins version ship with CSRF protection enabled out-of-the-box, so this library should enable crumbs by default to deal with that.

**Comment by dhdanno** [comment]
even with crumbs enabled I get errors...

> Stack trace:
> #0 /vendor/jenkins-khan/jenkins-api/src/Jenkins.php(265): JenkinsKhan\Jenkins->validateCurl(Resource id #18, 'Error trying to...')
> #1 //test.php(18): JenkinsKhan\Jenkins->launchJob('...')
> #2 {main}
>   thrown in /vendor/jenkins-khan/jenkins-api/src/Jenkins.php on line 837
